### ISSUE TITLE
Strange thing happens

### ISSUE THREAD

**Issue by stefanhusmann** [ianbrunelli/aur-updatebot#1]
Hello, 

thank you for your script, it seems to work fine for the most cases. But I have a problem when it comes to build my package lilypond-git in AUR4.

I run aurupbot the following way:

/bin/sh /usr/bin/aurupbot -n -u haawda

haawda is me in the AUR.

I have configured aurupbot not to use /tmp, but the directory I usually build in. 

The resulting logfile is too big to be posted to the usual pastbin services, so I try to post only the relevant parts of it here.

At  the beginning, I have a check in the configure run where aurupbot puts together a synthetic pat including the names of all my AUR4 packages. 

 checking builddir... /home/haawda/paketierung/maintained_by_me/emacs-xwidget-git/a2pdf/a2png/abcl/abcl-svn/agedu-svn/amaya-git/amberfish/amide/aoeui/arachnophilia/arora-git/asymptote-svn/auctex-git/autolatex/awka/barewm-git/biblesync/biblesync-git/bibtool-git/bibstuff/bibtex2html/bigloo-devel/birdfont/blackhole-git/bmpanel/btg/coffee-script-git/cauchy-hg/clickosquare/car/clisp-new-clx/dictionary/ding/dired/dkopp/dmake/dockboard-svn/doxymacs-git/duff/eel-language/eel-language-git/elk/emacs-babel-git/emacs-bookmarkplus-mode/emacs-calfw-git/emacs-chess-git/emacs-dbus-introspection/emacs-dbus-proxy/emacs-dvc-bzr/emacs-elscreen/emacs-elscreen-dired/emacs-elscreen-dnd/emacs-elscreen-gf/emacs-elscreen-goby/emacs-elscreen-howm/emacs-elscreen-server/emacs-elscreen-speedbar/emacs-elscreen-w3m/emacs-elscreen-wl/emacs-else-git/findwild/flybird/fontmatrix-git/fotoxx/fotoxx-maps/freefem++-hg/emacs-escreen/emacs-ess/emacs-ess-git/emacs-goby/emacs-goby-git/emacs-icicles/emacs-gnuplot-mode-git/emacs-identica-mode/ilisp/emacs-j-mode-git/emacs-jabber/emacs-jabber-git/emacs-js2-mode/emacs-js2-mode-git/emacs-lucid-git/g2/galaxy2/gambit-c-git/gauche-git/gdl-git/geda-gaf-unstable/glosstex/gnumeric-minimal/gnuplot-cvs/goffice-light/gqview-devel/grap/guile-emacs-git/emacs-mew/emacs-mew-git/emacs-mmm-mode-git/emacs-newlisp/emacs-newlisp-mode-git/emacs-org-mode-git/emacs-pkgbuild-mode-git/emacs-planner/emacs-planner-git/emacs-pov-mode/emacs-psgml/emacs-psvn/emacs-rudel-bzr/emacs-screencast-mode-git/emacs-sdcv/emacs-svg-clock/emacs-symbols-mode-git/emacs-tabbar-git/emacs-xclip/emacs-xlicense/emacs-yasnippet-git/emacs-yasnippet-latex-git/emact/emms-git/guile-git/emscripten-git/guile4emacs-git/engauge/guipdftk/epstool/gri/evilvte-git/halibut/eqe/emacs-rtf-mode/handbrake-cli-svn/handbrake-svn/harminv/hop/hop-devel/howl-editor/howl-editor-git/hp2xx/icon/icon-git/igv/iojs-git/inkscape-gtk3-bzr/j/jasspa-me/jpeginfo/jsword/jvlt/keytouch/keytouch-editor/lake-git/latex-mk/latex2e-help-texinfo/lbench/le-editor/le-editor-git/libmatio/librep-git/rep-gtk/rep-gtk-git/sawfish/sawfish-git/sawfish-misc-git/sawfish-pager/sawfish-pager-git/sawfish-session-dialog/sawfish-session-dialog-git/sawfish-theming-git/mailcrypt/man2texi/mandelbrot-gtk-git/mawk/maxima-git/meep/meh-git/mickey-scheme-git/minionpro/mk_vpp/mkbib/libsvg/mkcl-git/libsvg-cairo/mm-common-git/libxaw3dxft/mystuff/lilypond-devel/lilypond-devel-docs/lilypond-git/src/lilypond
checking for stepmake... ./stepmake  (${datarootdir}/stepmake not found)

Strangely enough, the build continues. But then a lot later it stalls with a similar step when some documentation wants to be built.

   && mpost -progname=mpost -ini /home/haawda/paketierung/maintained_by_me/emacs-xwidget-git/a2pdf/a2png/abcl/abcl-svn/agedu-svn/amaya-git/amberfish/amide/aoeui/arachnophilia/arora-git/asymptote-svn/auctex-git/autolatex/awka/barewm-git/biblesync/biblesync-git/bibtool-git/bibstuff/bibtex2html/bigloo-devel/birdfont/blackhole-git/bmpanel/btg/coffee-script-git/cauchy-hg/clickosquare/car/clisp-new-clx/dictionary/ding/dired/dkopp/dmake/dockboard-svn/doxymacs-git/duff/eel-language/eel-language-git/elk/emacs-babel-git/emacs-bookmarkplus-mode/emacs-calfw-git/emacs-chess-git/emacs-dbus-introspection/emacs-dbus-proxy/emacs-dvc-bzr/emacs-elscreen/emacs-elscreen-dired/emacs-elscreen-dnd/emacs-elscreen-gf/emacs-elscreen-goby/emacs-elscreen-howm/emacs-elscreen-server/emacs-elscreen-speedbar/emacs-elscreen-w3m/emacs-elscreen-wl/emacs-else-git/findwild/flybird/fontmatrix-git/fotoxx/fotoxx-maps/freefem++-hg/emacs-escreen/emacs-ess/emacs-ess-git/emacs-goby/emacs-goby-git/emacs-icicles/emacs-gnuplot-mode-git/emacs-identica-mode/ilisp/emacs-j-mode-git/emacs-jabber/emacs-jabber-git/emacs-js2-mode/emacs-js2-mode-git/emacs-lucid-git/g2/galaxy2/gambit-c-git/gauche-git/gdl-git/geda-gaf-unstable/glosstex/gnumeric-minimal/gnuplot-cvs/goffice-light/gqview-devel/grap/guile-emacs-git/emacs-mew/emacs-mew-git/emacs-mmm-mode-git/emacs-newlisp/emacs-newlisp-mode-git/emacs-org-mode-git/emacs-pkgbuild-mode-git/emacs-planner/emacs-planner-git/emacs-pov-mode/emacs-psgml/emacs-psvn/emacs-rudel-bzr/emacs-screencast-mode-git/emacs-sdcv/emacs-svg-clock/emacs-symbols-mode-git/emacs-tabbar-git/emacs-xclip/emacs-xlicense/emacs-yasnippet-git/emacs-yasnippet-latex-git/emact/emms-git/guile-git/emscripten-git/guile4emacs-git/engauge/guipdftk/epstool/gri/evilvte-git/halibut/eqe/emacs-rtf-mode/handbrake-cli-svn/handbrake-svn/harminv/hop/hop-devel/howl-editor/howl-editor-git/hp2xx/icon/icon-git/igv/iojs-git/inkscape-gtk3-bzr/j/jasspa-me/jpeginfo/jsword/jvlt/keytouch/keytouch-editor/lake-git/latex-mk/latex2e-help-texinfo/lbench/le-editor/le-editor-git/libmatio/librep-git/rep-gtk/rep-gtk-git/sawfish/sawfish-git/sawfish-misc-git/sawfish-pager/sawfish-pager-git/sawfish-session-dialog/sawfish-session-dialog-git/sawfish-theming-git/mailcrypt/man2texi/mandelbrot-gtk-git/mawk/maxima-git/meep/meh-git/mickey-scheme-git/minionpro/mk_vpp/mkbib/libsvg/mkcl-git/libsvg-cairo/mm-common-git/libxaw3dxft/mystuff/lilypond-devel/lilypond-devel-docs/lilypond-git/src/lilypond/mf/mf2pt1.mp \dump
This is MetaPost, version 1.902 (TeX Live 2014/Arch Linux) (kpathsea version 6.2.0)
! I can't open file `/home/haawda/paketierung/maintained_by_me/emacs-xwidget-gi
t/a2pdf/a2png/abcl/abcl-svn/agedu-svn/amaya-git/amberfish/amide/aoeui/arachnoph
ilia/arora-git/asymptote-svn/auctex-git/autolatex/awka/barewm-git/biblesync/bib
lesync-git/bibtool-git/bibstuff/bibtex2'.

The other packages seem not to have this problem, but also lilypond-git builds fine whe running a bare makepkg. 

Let me know if you have an idea what is going on here. Thanks in advance.

**Comment by brunelli** [comment]
Hey.

So, `aurupbot` is running a bare `makepkg` too (I still have to add an option to pass parameters to `makepkg`). Therefore, if it's building outside `aurupbot`, it should be built the same way by the script.

Could you please run it using the default directory (`/tmp/aurupbot-$USER`) and tell me if the output is the same?

I'll try to take a deeper look on this later today.

Cheers, Ian.

**Edit**: You may want to add `flex` to the list of makedepends.

`ERROR: Please install required programs:  flex FlexLexer.h (flex package)`

**Edit 2**: The line `checking for stepmake... ./stepmake  (${datarootdir}/stepmake not found)` seems to be irrelevant here, as it appears while running `makepkg` too.

**Edit 3**: The package was successfully built here with `aurupbot lilypond-git -n` using the default directory. Here is the `mpost` part:

```
&& mpost -progname=mpost -ini /tmp/aurupbot-ian/lilypond-git/src/lilypond/mf/mf2pt1.mp \\dump
This is MetaPost, version 1.902 (TeX Live 2014/Arch Linux) (kpathsea version 6.2.0)
(/tmp/aurupbot-ian/lilypond-git/src/lilypond/mf/mf2pt1.mp
(/usr/share/texmf-dist/metapost/base/mfplain.mp
Preloading the plain base, version 0.99: preliminaries,
 basic constants and mathematical macros,
 macros for converting units,
 macros and tables for various modes of operation,
 macros for drawing and filling,
 macros for proof labels and rules,
 macros for character and font administration,
and a few last-minute items.))
Transcript written on mf2pt1.log.
```

Does the file `/home/haawda/paketierung/maintained_by_me/emacs-xwidget-git/a2pdf/a2png/abcl/abcl-svn/agedu-svn/amaya-git/amberfish/amide/aoeui/arachnophilia/arora-git/asymptote-svn/auctex-git/autolatex/awka/barewm-git/biblesync/biblesync-git/bibtool-git/bibstuff/bibtex2` exists?

Could you run a `makepkg` and paste the `mpost` part of the output here?

**Comment by stefanhusmann** [comment]
> Could you please run it using the default directory (/tmp/aurupbot-$USER) and tell me if the output is >the same?

Sorry, I run out of disk space if I do so.

> Edit: You may want to add flex to the list of makedepends.
> Technically yes, but flex is in base-devel, so it should be installed when usng AUR.
> 
> Edit 3: The package was successfully built here with aurupbot lilypond-git -n using the default 
> directory. Here is the mpost part:
> I also can build lilypond-git that way. The problem seems only occur if I use the -u option and try to process _all_ my AUR packages. The problem is not related to lilypond-git, and occurs with other packages also. 
> 
> Does the file /home/haawda/paketierung/maintained_by_me/emacs-xwidget-git/a2pdf/a2png
> /abcl/abcl-svn/agedu-svn/amaya-git/amberfish/amide/aoeui/arachnophilia/arora-git/asymptote-
> svn/auctex-git/autolatex/awka/barewm-git/biblesync/biblesync-git/bibtool-git/bibstuff/bibtex2 exists?
> no, I have the path /home/haawda/paketierung/maintained_by_me, where my packages live, and so subdirectories emacs-xwidget-git, a2pdf, a2png... bibstuff exist. The "bibtex2" seems to be a truncation of "bibtex2html"

**Comment by brunelli** [comment]
> I also can build lilypond-git that way. The problem seems only occur if I use the -u option and try to process all my AUR packages. The problem is not related to lilypond-git, and occurs with other packages also.

Okay, could you do it and then post the `mpost` part here?

**Comment by stefanhusmann** [comment]
-----BEGIN PGP MESSAGE-----
Charset: utf-8
Version: GnuPG v2

hQIMA+yv0Wm5EeVyAQ/+JAKIv7oJJ+eymCd3vf7yHG8Uoy7Zxg6k68UkdD7BkaeV
FDhN7pby3rnesQ9y2SGQta5v95Hk4UWWyOohjSD788agSZI30IekwgT2rdcYNqFQ
xvPA5gxLLjnyAhnce2i4v1XwtnAWZDuT/AzTDR2JL4LPAm1WyJ4gdZMbx30vk4sV
H1NuHCjEaDa/LKm2o0pd59ITrGzSTxF8HCCWB117Z/xaUs/caJbJ2OdJvgrlKQpw
nydDmASwO1J+lmnCKT/araNOfH0KOms1sv9l0R77I1mT1mKBk8RIuhRCufF6r8di
9CVuqE7X0gZVK33rXqBW8oxSwJwOadmebYlBO84HPBSBS56aM2L4JG2Re3+Aig5j
dotueworyxi9WR+wr520v6cYgqdAjTbcLVH1v0qPBM0nnPTGcaEbSFrTCTJrZRgh
G33koNxMW8nsAxRXUOIX7dK1iuNjGgfK7gogfVib+0+NayQ1ptWCbyd78wW14M5R
hrZxiaREA5z/YmF9eDp1N3z6m7dodpJxYIHnMEEHI986EvXk6bK54cBFzC/1PyBW
dsS9Qsmyh5fgdkKMmKmAL16u281qzQim2CNWo1b6qmx98THA/MTv1wia2SfjxbuO
IoskZRFSnNjzOPYsgYhN+TlQU5eV3tD9SZe1YyRjpqn9hxEyr3GiOv8gEB54t0rS
6gEImGSPPnAHNSpaOw/NObW8BVihWhqC/rg+csu7p1LOWLrQdOwxPcTTs/RtanQE
3OG4ckKxw4VjlBdJOVD0s1J0ivBu52Qh3fGykSEtZeR1xMgwS2v7x7n9M4zBqKM+
l1RaCCqofxwIlqQIA8sXwjAKg1I0dvY/7hDHRMcTpwNoIxG0/lqr0vzyufhimW1s
R8AdXq1ITXPwCRtRW8Vnf4x7j7DTZCpbONS8Yr0HMNto1m1mBg2VZ6FoGbiNm36d
8fe+FVRMduLyKbBMw+aAu6Y0RNqKrmMg94zxAltzjdDgoXjxOcz2LJz4KJLTRmQE
mYIheGCWp2QHwc5PFHWZDAYGyFk8e4DLLtheMZxKrdxrcTe9FPcejb3Wv5AyIZKq
NyjFR0vCdwsYXuWJHDorRsLqdZrkqbAUkP+SXT1iyct7SPX5Ra+Ne9mkvpqJYBo7
SPgojoGQbCj8fgtqmUbHwGkmYL7u783nypNA8I5Ff7n/he06Xvgu+m15z01ufKjJ
qDQOy3qzrTrTylJsP5WAHLzPsAOml0o/BlHAsRS7KA5OZuRb9ghnya2warHI/VUj
OjeuJKfSmedb3wNAxG9xRj5H3AGmJJD2aTjnl4COqrP+FZRvy+WrlARgT1XgDrrm
uqE140fltqJ6infQ/lGO+xuj2xwQvcMxyI1EVyjZO5mqSGAT40bTprRJvKmpluKD
0MT+sAkHkI1fzRwrN2B6j0vaOkcwxcg5DSvfF+y9uRaYjZGi62lxSgGFwKpCXH0C
0oJsJDDVqJ+MipfR4M2vcieCy4oTpV8tPY+cQfStuB7GigGznneRaGPfHuhALKmK
98zIGSSTanO4FjTuZHY80vcxmOpMUsYneMmS9BUg+E7lOyvB3Rd4rdVeXUng/TFS
GIxcyuBXz8whn+FXESqd32h5AHLl1SuAknTDNumeLLKVETGU+30i7dSiRiuelKuh
Il3x+ktNkzT5Ht0EWuP1tivARZuyTRlYNn8LrLu/aWxbwSui/J8/WGyUDeJtbmDq
t+SBddif5pRq9lR8cq8i0K3uLwTNq0lB/3ZD68KTT2AQWsgAGjCLpTEBsOKsQb/T
WcqQPvTpQyZnHnQ0gdGjvdRAfLD0bH2S/gMVwN56liYy49HXRE3WjbBhwfQSt/zo
shxeG9j2iPUsLM41kOVDK+XZEM/utQ5RyDMQntiS3GiCKfh2mYOj/CSV3Ah0mIXH
VPTA3ivhZ13IkMqTkdr/pDW6ZMJ0Z18TWgkUCBg4vEoPbQEr1GilosuucaT9zCB3
gjzpv0ClbgKGWRpNkuV2FZLSIZl1tY0WK3EvT7LPB6HHMYV3Fso49pZYF+aiycsX
CPCSdU4mfRY5u0TcS1uWDXBFBeqca4NChnghsni5UhtmEg1LGUFE3Tw9P6xp64iz
pK6gNEJ7865zitZRaJwuM3S7jX9veAPuUtBmXBpEV7e0ASNJ0zDH
=6WV8
-----END PGP MESSAGE-----

**Comment by brunelli** [comment]
Your last comment is encrypted...

**Comment by brunelli** [comment]
@stefanhusmann Could you please get the latest version from `master` and tell me if `aurupbot -n -u haawda` is working properly now?

**Comment by stefanhusmann** [comment]
Yes, it works fine now, many thanks for your help and the great script.
