### ISSUE TITLE
Strange warning about changelog

### ISSUE THREAD

**Issue by stefanhusmann** [ianbrunelli/aur-updatebot#10]
When I build my package emacs-ess-git, the output is

emacs-ess-git is out-of-date (15.03.1.223.g7c2813e -> 15.03.1.224.g6a68660).
:: Building package
Successfully built.
:: Checking package with namcap
Namcap returned 2 warning(s). See "/home/haawda/paketierung/meine_Pakete/emacs-ess-git_namcap.log" for details.
:: Creating changelog from Git commits
/usr/bin/aurupbot: line 169: printf: `y': invalid format character
:: Pushing new version to AUR

The weird thing is: there is no "y" in line 169 of the aurupbot script.

**Comment by stefanhusmann** [comment]
P.S. this issue is not very important, the script works well. It is just a little annoying.

**Comment by stefanhusmann** [comment]
And it is not always th 'y', but sometimes other letters.

maxima-git is out-of-date (5.37.1.59.g705913b -> 5.37.1.60.g71ccd50).
:: Building package
Successfully built.
:: Checking package with namcap
Namcap returned 20 warning(s). See "/home/haawda/paketierung/meine_Pakete/maxima-git_namcap.log" for details.
:: Creating changelog from Git commits
/usr/bin/aurupbot: line 169: printf: `p': invalid format character
:: Pushing new version to AUR
[master 28b13fb] Updated version (5.37.1.59.g705913b -> 5.37.1.60.g71ccd50).
 Author: AUR Update Bot stefan-husmann@t-online.de
 2 files changed, 2 insertions(+), 2 deletions(-)
To ssh://aur@aur.archlinux.org/maxima-git.git
   5d4a54e..28b13fb  master -> master

**Comment by brunelli** [comment]
This is an issue when expanding the variable (although there's no "y" in line 169, there's the `COMMIT_LOG` variable). Could you please replace line 169 with the following line and tell me if it solves the issue?

```
CHANGELOG=$( printf "\n\nChangelog\n=========\n"; cat <<< "$COMMIT_LOG" ); }
```

**Comment by stefanhusmann** [comment]
Yes, the line fixes it. Thanks.

**Comment by brunelli** [comment]
Great! I'll update the repo as soon as I get home. Thanks for the report.
