### ISSUE TITLE
Version 1.2.1 has problems with my ssh configuration, version 1.0.2 works fine

### ISSUE THREAD

**Issue by stefanhusmann** [ianbrunelli/aur-updatebot#6]
Version 1.2. shows up for every package I try to build the following:

=> Cloning the AUR repository for arachnophilia
no such identity: /home/haawda/.ssh/sshanocvs: No such file or directory
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Version 1.0.2 works fine with the same configuration.

**Comment by brunelli** [comment]
I changed the URL (from `aur4.archlinux.org` to `aur.archlinux.org`), so this may be the problem.

Could you please edit your `/home/haawda/.ssh/config` file replacing the old URL by the new one and tell me if this fixes the issue?

**Comment by stefanhusmann** [comment]
I did so, but no change.

**Comment by brunelli** [comment]
Well, that's strange...

If you edit the script `/usr/bin/aurupbot` replacing both occurrences of `aur.archlinux.org` by `aur4.archlinux.org` it works, right?

**Comment by brunelli** [comment]
Oh, okay!

The problem is your `IdentityFile` is invalid. Make sure the entry to `aur.archlinux.org` in `$HOME/.ssh/config` is pointing to an existing file... You should use the same file you're using for `aur4.archlinux.org`.

**Comment by stefanhusmann** [comment]
You are right, there was a typo. I fixed it, but now aurupbot 1.2.1 claims
==> Cloning the AUR repository for abcl-svn
fatal: destination path '/home/haawda/paketierung/maintained_by_me/abcl-svn' already exists and is not an empty directory.
This is done for some, but not for all packages.

**Comment by brunelli** [comment]
Can you confirm that `/home/haawda/paketierung/maintained_by_me/abcl-svn` indeed exists and its a clone of `abcl-svn`?

It should've been removed before reaching this point on the script execution.

Your setup is not using the `REUSE_DIRS` options, right?

**Comment by stefanhusmann** [comment]
The reuse option was the culprit. I today edited the aurupbotrc, and used an editor that did not show the last letter of the last line of the file, the "e" in "true" of the REUSE-DIRS option so I added it. Now I just saw that there where two letters "e". 
The other question: I am quite sure that the directory existed, but I am not sure git gets puzzled if I try to clone from aur.archlinux.org when the local repo has been cloned from aur4.archlinux.org.

**Comment by brunelli** [comment]
Well, unless you removed the `aur4.archlinux.org` entry from your `.ssh/config`, you should have no issues. I would edit the URL in `.git/config` for every package, though, just for the sake of it (who knows for how long the aur4 subdomain will be alive):

`sed -i "s/ssh:\/\/aur@aur4/ssh:\/\/aur@aur/g" /home/haawda/paketierung/maintained_by_me/*/.git/config`

And then you can remove the `aur4` on your `.ssh/config`.
